module.exports = {
  'const-parameters': true,
  // 'early-exit': [true, { 'max-length': 4 }],
  // 'ext-curly': true,
  'naming-convention': true,
  'no-as-type-assertion': true,
  'no-accessor-recursion': true,
  'no-collapsible-if': true,
  'no-else-after-return': true,
  'no-return-undefined': true,
  'no-static-this': true,
  'no-unnecessary-else': true,
  'no-unnecessary-type-annotation': true,
  'no-unused': [true, 'ignore-parameters'],
  // 'no-var-before-return': true,
  'object-shorthand-properties-first': true,
  'parameter-properties': true,
  'prefer-const-enum': true,
  'prefer-while': true,
}
