import GOOGLE_TRANSLATE_SQUARE from '~/assets/img/providerIcon/googleTranslate/type_1_translate_281759.svg'
import GOOGLE_TRANSLATE_CIRCLE from '~/assets/img/providerIcon/googleTranslate/type_3_google_814137.svg'
import TRANSLATE_ICON from '~/assets/img/translate_2406387.svg'
import MAG_ICON from '~/assets/img/magnify_929469.svg'

export enum PROVIDER {
  ICIBA = 'ICIBA',
  GOOGLE_DICT = 'GOOGLE_DICT',
  GOOGLE_TRANSLATE = 'GOOGLE_TRANSLATE',
  BAIDU_TRANSLATE = 'BAIDU_TRANSLATE',
  SOUGOU_TRANSLATE = 'SOUGOU_TRANSLATE',
  URBAN_DICTIONARY = 'URBAN_DICTIONARY',
  BING_TRANSLATE = 'BING_TRANSLATE',
  VOCABULARY = 'VOCABULARY',
}
export const PROVIDER_MAP = {
  [PROVIDER.ICIBA]: 'iciba',
  [PROVIDER.GOOGLE_DICT]: 'google字典',
  [PROVIDER.GOOGLE_TRANSLATE]: 'google翻译',
  [PROVIDER.BAIDU_TRANSLATE]: '百度翻译',
  [PROVIDER.SOUGOU_TRANSLATE]: '搜狗翻译',
  [PROVIDER.URBAN_DICTIONARY]: 'urban dictionary',
  [PROVIDER.BING_TRANSLATE]: 'bing 翻译',
  [PROVIDER.VOCABULARY]: 'vocabulary',
}
export const providerOptions = Object
  .entries(PROVIDER_MAP)
  .map(([k, v]) => ({
    label: v,
    key: k,
  })) as Array<{ key: PROVIDER, label: string }>

export const allProviders = providerOptions.map((v) => v.key)

type Keys = keyof typeof PROVIDER_MAP
export type ProviderTestFunc<T extends Keys> = (p: T) => any
export type ProviderTest = ProviderTestFunc<PROVIDER>

export enum GOOGLE_TRANSLATE_HOST {
  GOOGLE_COM = 'GOOGLE_COM',
  GOOGLE_CN = 'GOOGLE_CN',
}
export const GOOGLE_TRANSLATE_HOST_MAP = {
  [GOOGLE_TRANSLATE_HOST.GOOGLE_COM]: 'translate.google.com',
  [GOOGLE_TRANSLATE_HOST.GOOGLE_CN]: 'translate.google.cn',
}

export enum GOOGLE_DICT_FOLD_STATUS {
  UNFOLD = '0',
  FOLD_THESAURUS = '1',
  FOLD_EXAMPLES = '2',
  FOLD_SUBSENSE = '3',
}

export const GOOGLE_DICT_FOLD_STATUS_NEXT_MAP = {
  [GOOGLE_DICT_FOLD_STATUS.UNFOLD]: GOOGLE_DICT_FOLD_STATUS.FOLD_THESAURUS,
  [GOOGLE_DICT_FOLD_STATUS.FOLD_THESAURUS]: GOOGLE_DICT_FOLD_STATUS.FOLD_EXAMPLES,
  [GOOGLE_DICT_FOLD_STATUS.FOLD_EXAMPLES]: GOOGLE_DICT_FOLD_STATUS.FOLD_SUBSENSE,
  [GOOGLE_DICT_FOLD_STATUS.FOLD_SUBSENSE]: GOOGLE_DICT_FOLD_STATUS.FOLD_SUBSENSE,
}

export const GOOGLE_DICT_FOLD_STATUS_PREV_MAP = {
  [GOOGLE_DICT_FOLD_STATUS.UNFOLD]: GOOGLE_DICT_FOLD_STATUS.UNFOLD,
  [GOOGLE_DICT_FOLD_STATUS.FOLD_THESAURUS]: GOOGLE_DICT_FOLD_STATUS.UNFOLD,
  [GOOGLE_DICT_FOLD_STATUS.FOLD_EXAMPLES]: GOOGLE_DICT_FOLD_STATUS.FOLD_THESAURUS,
  [GOOGLE_DICT_FOLD_STATUS.FOLD_SUBSENSE]: GOOGLE_DICT_FOLD_STATUS.FOLD_EXAMPLES,
}

export const GOOGLE_DICT_FOLD_STATUS_MAP = {
  [GOOGLE_DICT_FOLD_STATUS.UNFOLD]: '展开',
  [GOOGLE_DICT_FOLD_STATUS.FOLD_SUBSENSE]: '折叠释义子项',
  [GOOGLE_DICT_FOLD_STATUS.FOLD_EXAMPLES]: '折叠子项和例句',
  [GOOGLE_DICT_FOLD_STATUS.FOLD_THESAURUS]: '折叠子项、例句和同反义词',
}

export enum ICIBA_CIRCLE_ICON {
  DEFAULT = 'default',
  GOOGLE_TRANSLATE_SQUARE = 'gtsquare',
  GOOGLE_TRANSLATE_CIRCLE = 'gtcircle',
  GOOGLE_TRANSLATE_TEXT = 'gttext',
  MAG_ICON = 'icondic',
}

export const ICIBA_CIRCLE_ICON_MAP = {
  [ICIBA_CIRCLE_ICON.DEFAULT]: '',
  [ICIBA_CIRCLE_ICON.GOOGLE_TRANSLATE_SQUARE]: GOOGLE_TRANSLATE_SQUARE,
  [ICIBA_CIRCLE_ICON.GOOGLE_TRANSLATE_CIRCLE]: GOOGLE_TRANSLATE_CIRCLE,
  [ICIBA_CIRCLE_ICON.GOOGLE_TRANSLATE_TEXT]: TRANSLATE_ICON,
  [ICIBA_CIRCLE_ICON.MAG_ICON]: MAG_ICON,
}

export const ICIBA_CIRCLE_ICON_TYPE_MAP: Record<ICIBA_CIRCLE_ICON, 'square' | 'circle'> = {
  [ICIBA_CIRCLE_ICON.DEFAULT]: 'circle',
  [ICIBA_CIRCLE_ICON.GOOGLE_TRANSLATE_SQUARE]: 'square',
  [ICIBA_CIRCLE_ICON.GOOGLE_TRANSLATE_CIRCLE]: 'circle',
  [ICIBA_CIRCLE_ICON.GOOGLE_TRANSLATE_TEXT]: 'square',
  [ICIBA_CIRCLE_ICON.MAG_ICON]: 'square',
}

export enum GM_STORE_KEY {
  STORE = 'iciba_store',
  SOUGOU_SECCODE = 'sougou_seccode',
  HISTORY = 'history',
}
