// Generated by https://quicktype.io

export interface ExampleResult {
  status: number
  result: {
    totalHits: number
    sentences: Array<Sentence>
  }
}

export interface Sentence {
  volume: {
    wordCount: number
    corpus: {
      name: string
      id: string
    }
    domains?: Array<Domain>
    sentenceCount: number
    title: string
    dateAdded: string
    datePublished: string
    domain?: Domain
    id: number
    locator: string
    author?: string
  }
  sentence: string
  corpusId: string
  volumeOffset: number
  offsets: Array<number>
  volumeId: number
}

export enum Domain {
  A = 'A',
  N = 'N',
  S = 'S',
  T = 'T',
}
